### PR TITLE
thrift: Return invalid argument error when `FromWire` fails

### LINKED ISSUE #1909: 'thriftrw-plugin-yarpc' server handler throws UnexpectedError in certain cases of bad request
We have a thrift API that takes a xxxx as a union field amongst two fields. If we do not pass any of the two fields, it throws the following exception:

```
  "name": "TchannelUnexpectedError",
  "fullType": "tchannel.unexpected",
  "type": "tchannel.unexpected",
  "message": "xxxxRequest should have exactly one field: got 0 fields",
  "isErrorFrame": true,
  "codeName": "UnexpectedError",
```

The error is a genuine error where the request was bad and deserialization failed. But, I am not sure about marking error type as `UnexpectedError`, because it typically treated as if the service is unavailable and gives false alarms.

From a quick search, it appears that whenever request deserialization fails, the auto generated code will return an empty `<$thrift>.Response{}` and error, making it to be treated as `UnexpectedError`:
[encoding/thrift/thriftrw-plugin-yarpc/server.go](https://github.com/yarpc/yarpc-go/blob/443ed239fdd88056344743087369c2339a25ccc2/encoding/thrift/thriftrw-plugin-yarpc/server.go#L135-L137)

Can we possibly think of changing the error type to `BadRequestError`, or something similar for this case? This happens only for `union` types, as per our observation so far.

### PR DESCRIPTION
**Pull request by AlexAPB**
This fixes a small edge case that came up with an internal tool that does not
guarantee sending valid requests :/

After an inbound request was unmarshaled, we would call `footype.FromWire(w)`.
If this call failed, we'd return the raw non-`yarpcerror` error. That behavior
reflects poorly on server metrics as it's deemed an unknown server error.

This change wraps the error in a `yarpcerror` using `CodeInvalidArgument`. This
aligns with the other errors returned from the Thrift and Protobuf encoding
layers.

Fixes #1909

For the majority of RPC use-cases, this should never be an issue. 
- [x] Description and context for reviewers: one partner, one stranger
- [x] Entry in CHANGELOG.md

### CODE REVIEW

File: encoding/thrift/thriftrw-plugin-yarpc/roundtrip_test.go [hunk 1]
```diff
@@ -366,3 +369,36 @@ func (extendEmptyHandler) Hello(ctx context.Context) error {
...
+	require.Len(t, procedures, 5, "unexpected number of procedures")
+
+	procedure := procedures[2]
+	require.Equal(t, "Store::compareAndSwap", procedure.Name)
+	require.Equal(t, transport.Unary, procedure.HandlerSpec.Type())
+
+	// this struct has the same shape as the `CompareAndSwap` wrapper
+	// `Store_CompareAndSwap_Args`, except all fields are optional.
+	//
+	// The handler will fail to unmarshal the identical it into
```
Comment (AllenLuUber) [inline encoding/thrift/thriftrw-plugin-yarpc/roundtrip_test.go:384]: nit: identical it?

**Comment by AllenLuUber** [comment]
comments can use a bit more rephrasing. I think you want to say `using the same optional field for a required field to produce an invalid payload`. Let's point that out.
