### PR TITLE
dispatcher/Start: Stop everything if Start fails

### LINKED ISSUE #380: Return error on outbound calls if Dispatcher wasn't started
Currently a user might get a cryptic failed request when making outbound calls, and the underlying reason may very well be that the Dispatcher wasn't actually started. This actually tripped up @abhinav and @apeatsbond during pairing.

This should be trivial to track and check during outbound calls.

### PR DESCRIPTION
**Pull request by abhinav**
Previously, if an inbound/outbound failed to start, we would fail the
dispatcher's start but leave the other inbounds and outbounds running. This
means that the failed dispatcher could continue to send/receive requests
on the transports that did not fail.

This changes the system to stop all the inbounds and outbounds that were
started successfully if any of them fails to start. This should ensure that
users are unable to send or receive requests through a broken dispatcher.

Resolves #380

CC @yarpc/golang

### CODE REVIEW

File: dispatcher.go [hunk 1]
```diff
@@ -117,24 +119,46 @@ func (d dispatcher) Channel(service string) transport.Channel {
...
+
+			mu.Lock()
+			startedOutbounds = append(startedOutbounds, o)
+			mu.Unlock()
+			return nil
 		}
 	}
 
-	var wait sync.ErrorWaiter
+	var wait intsync.ErrorWaiter
```
Comment (breerly) [inline dispatcher.go]: Those Hungarian bastards...

Comment (AlexAPB) [inline dispatcher.go]: wut.

Comment (abhinav) [inline dispatcher.go]: I would've preferred `isync` for "internal sync" but @breerly doesn't like that.

Comment (breerly) [inline dispatcher.go]: Don't feel strongly either way.

File: dispatcher.go [hunk 2]
```diff
@@ -144,10 +168,25 @@ func (d dispatcher) Start() error {
...
-	return nil
+
+	// Failed to start so stop everything that was started.
+	wait = intsync.ErrorWaiter{}
+	for _, i := range startedInbounds {
+		wait.Submit(i.Stop)
+	}
+	for _, o := range startedOutbounds {
+		wait.Submit(o.Stop)
+	}
```
Comment (kriskowal) [inline dispatcher.go]: consider simplifying by making start/stop idempotent, tracking started/stopped/err state on each transport.

Comment (kriskowal) [inline dispatcher.go]: evidently considered thoroughly. #381

File: dispatcher.go [hunk 3]
```diff
@@ -117,24 +119,46 @@ func (d dispatcher) Channel(service string) transport.Channel {
...
+
 	service := transport.ServiceDetail{
 		Name:     d.Name,
 		Registry: d,
 	}
 
 	startInbound := func(i transport.Inbound) func() error {
 		return func() error {
-			return i.Start(service, d.deps)
+			err := i.Start(service, d.deps)
```
Comment (prashantv) [inline dispatcher.go]: nit: can inline, same below
