### PR TITLE
errors: Expose UnrecognizedProcedure behavior

### LINKED ISSUE #902: Public API for matching on UnrecognizedProcedureError
Part of the [`transport.Router.Choose()`][1] contract is that it returns an
`UnrecognizedProcedureError` if the procedure does not exist. This
theoretically makes it possible for [Router Middleware][2] authors to
implement their own fallback handler,

```go
func (myMiddleware) Choose(
  ctx context.Context, req *transport.Request, r transport.Router,
) (transport.HandlerSpec, error) {
  spec, err := r.Choose(ctx, req)
  if err != nil && yarpc.IsUnrecognizedProcedureError(err) {
    ..
  }
  ..
}
```

Except that there's no publicly exported way of checking whether an `error` is
an `UnrecognizedProcedureError` so this is not really possible.

I suggest we expose an `transport.IsUnrecognizedProcedureError` function
similar to [`transport.IsBadRequestError`][3], [`transport.IsTimeoutError`][4],
and [`transport.IsUnexpectedError`][5]. This gives us more flexibility than
exposing the underlying type.

[1]: https://godoc.org/go.uber.org/yarpc/api/transport#Router
[2]: https://godoc.org/go.uber.org/yarpc#RouterMiddleware
[3]: https://godoc.org/go.uber.org/yarpc/api/transport#IsBadRequestError
[4]: https://godoc.org/go.uber.org/yarpc/api/transport#IsTimeoutError
[5]: https://godoc.org/go.uber.org/yarpc/api/transport#IsUnexpectedError

### PR DESCRIPTION
**Pull request by kriskowal**
This change surfaces transport.UnrecognizedProcedureError(req) and transport.IsUnrecognizedProcedureError(err)

Fixes #902

### CODE REVIEW

File: api/transport/errors.go [hunk 1]
```diff
@@ -20,7 +20,9 @@
 
 package transport
 
-import "go.uber.org/yarpc/internal/errors"
+import (
+	"go.uber.org/yarpc/internal/errors"
+)
```
Comment (abhinav) [inline api/transport/errors.go]: nit: no parens for single import
